### ISSUE TITLE
Add ionicon mention? and how about size?

### ISSUE THREAD

**Issue by wyattp11** [coryasilva/Leaflet.ExtraMarkers#12]
Adding ionicons was easy, simply use "ion" for prefix. Mention that in readme?

Also, how can I control marker size? Custom class?

Thanks!

**Comment by coryasilva** [comment]
Currently there is no size control.  See #3.  I was thinking that while I could make say 5 sizes of markers it would be much more useful to just use SVG markers.  

See https://github.com/hiasinho/Leaflet.vector-markers  

I want to eventually incorporate SVG markers and icons along with SVG morphing but I will need to wait until I get contracted for another mapping project...
