### ISSUE TITLE
Release 1.0.2 zip file contains a wrong reference in bower.json

### ISSUE THREAD

**Issue by marfago** [coryasilva/Leaflet.ExtraMarkers#13]
The main section in bower.json file in 1.0.2 zip file is:
"main": [
        "src/leaflet.awesome-markers.css",
        "src/leaflet.awesome-markers.less",
        "src/leaflet.awesome-markers.js"
    ],

and prevents wiredep to work properly with dependencies.

**Comment by coryasilva** [comment]
Not sure how to fix that, should I just roll a new release?

**Comment by marfago** [comment]
Yes please.

**Comment by coryasilva** [comment]
A new release was just published with the correct binaries.
