### ISSUE TITLE
Image path error in CSS

### ISSUE THREAD

**Issue by realrnjs** [coryasilva/Leaflet.ExtraMarkers#19]
HI

Image path error in leaflet.extra-markers.css
.extra-marker{background:url('images/markers_default.png')

../img/markers_default.png  ?

**Comment by coryasilva** [comment]
Yeah, that was definitely an error.  Never noticed...

**Comment by realrnjs** [comment]
Thanks.

**Comment by realrnjs** [comment]
Hi. 
wrong path ^^;;

.extra-marker{background:url("/img/markers_default.png") ?? 

.extra-marker{background:url("/img/markers_default.png") !!

**Comment by dgorissen** [comment]
+1 confirm the generated css file still has the wrong paths

**Comment by coryasilva** [comment]
Okay it should work correctly now
