### ISSUE TITLE
text is too low

### ISSUE THREAD

**Issue by spifftek70** [coryasilva/Leaflet.ExtraMarkers#21]
The numbers I'm inputing are too low on the marker.  How can I raise them?

![screen shot 2016-03-18 at 8 54 36 am](https://cloud.githubusercontent.com/assets/11727190/13879791/4f3e0296-ece7-11e5-9a5d-fc80f389454e.png)

**Comment by coryasilva** [comment]
Admittedly this feature needs some work; currently you must only use the font-awesome as a prefix.
````  
  L.marker([32.995, -117.255], {
    icon: L.ExtraMarkers.icon({
        icon: 'fa-number',
        shape: 'penta',
        prefix: 'fa',
        markerColor: 'green',
        number: '1'
    })


I will roll an update to resolve this and consider this issue open.

**Comment by coryasilva** [comment]
You no longer need to add the `prefix: 'fa'`
