### ISSUE TITLE
Possible Hex MarkerColors

### ISSUE THREAD

**Issue by riostevenson** [coryasilva/Leaflet.ExtraMarkers#23]
Is there anyway you can think of that I could use hex colors for markerColor instead of the predefined colors listed?

**Comment by coryasilva** [comment]
I think you have a couple of options here.
**Option: 1**
Edit the adobe illustrator file to change the colors and then burn a new sprite image. (I simply export the Illustrator Artboards as PNGs)

**Option: 2**
I have not had time to gracefully create an SVG implementation but the feature that was merged in #18 give you a lot of flexibility.

**Comment by riostevenson** [comment]
@coryasilva Thank you very much for your reply and your guidance I initially thought of doing the first option but had no idea about the 2nd option I will have to do some more research... but thank you very much for your great contribution

**Comment by coryasilva** [comment]
No problem man, yeah that pull request from @ccoenen is pretty useful.
