### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by jecheverria** [coryasilva/Leaflet.ExtraMarkers#36]
hi, i would like to use font awesome 5, is it possible to do it?
thanks

**Comment by coryasilva** [comment]
For the webfont version we would have to add some css [here](https://github.com/coryasilva/Leaflet.ExtraMarkers/blob/master/src/assets/less/leaflet.extra-markers.less#L50) to handle the new classes `.fa, .fab, .fal, .far, .fas`:

I am not sure about the SVG options, are you using those?

**Comment by jecheverria** [comment]
Thank you!
