### ISSUE TITLE
Publish 1.0.8 on npm

### ISSUE THREAD

**Issue by cooljeffro** [coryasilva/Leaflet.ExtraMarkers#37]
Any possibility of publishing 1.0.8 to npm? I'd like to use the Typescript definitions.

**Comment by coryasilva** [comment]
Of course, but... I am tracking down the guy who initially published `leaflet-extra-markers` and requesting him to add me as an owner.  As soon as I get it added I will publish it for you.

**Comment by coryasilva** [comment]
Okay I had to do some cleanup for that but v1.0.9 has been published

**Comment by cooljeffro** [comment]
Thanks! That also fixed a css issue for me 😀
