### ISSUE TITLE
Icons are offset from the marker

### ISSUE THREAD

**Issue by stevevance** [coryasilva/Leaflet.ExtraMarkers#39]
<img width="159" alt="image" src="https://user-images.githubusercontent.com/1330459/72373809-a2294d00-36ce-11ea-9333-2545a9df426a.png">

I am using ExtraMarkers 1.0.5 release, and Font Awesome v5.x. 
The Extra Marker appears about 15 pixels above where it should be if it was centered in the marker. 

I am pretty sure that I haven't made any custom style definitions in my CSS that would affect this. You can see the code on http://chicagocityscape.com

**Comment by coryasilva** [comment]
seems like I did not cover the svg icons...

```css
.extra-marker .svg-inline--fa {
    margin-top: 12px;
}
```

Something like this should work.  Pull request?

**Comment by coryasilva** [comment]
fixed in v1.2.0+
