### ISSUE TITLE
problem with svg mode in firefox 

### ISSUE THREAD

**Issue by gabor-dev** [coryasilva/Leaflet.ExtraMarkers#41]
Hi,
When I use svg in markers with the newest version 1.0.9 in Firefox I see the svg circle sprite and the old circle image in the same time (slipped vertically with some 10 pixels) and the number <i></i> under them slipped down outside of the sprite.
However this is ok on Chrome.
This is the definition of the marker:
`{ icon: 'fa-number', shape: 'circle', markerColor: this.points[index].color, number: this.points[index].icon, iconColor: this.points[index].textcolor, svg:true }`

with a modified older css version it displays ok on firefox, but not on chrome:
[leaflet.extra-markers.GOOD_WITH_FIREFOX_BAD_WITH_CHROME.zip](https://github.com/coryasilva/Leaflet.ExtraMarkers/files/4095484/leaflet.extra-markers.GOOD_WITH_FIREFOX_BAD_WITH_CHROME.zip)

My firefox is v.72.01. 64 bit

**Comment by coryasilva** [comment]
Closing as fixed in v1.20+
