### ISSUE TITLE
leaflet.extra-markers.d.ts typescript error

### ISSUE THREAD

**Issue by cstaszak-logicboostlabs** [coryasilva/Leaflet.ExtraMarkers#44]
In `leaflet.extra-markers.d.ts`, should the declaration `iconRotation?: numeric;` be `iconRotation?: number;`?

**Comment by coryasilva** [comment]
Dammit!  Thanks for catching that.  I will try to get to it this week.
(Meetings all day rest of the week).

**Comment by cstaszak-logicboostlabs** [comment]
Thank you for your work here, we'll pick up your fix whenever it's in place.
In the meantime, reverting to 1.1.0 gets the job done with no hassle.
