### ISSUE TITLE
When I applied the innerHTML prop, a dummy '>' is shown.

### ISSUE THREAD

**Issue by JeongJun-Lee** [coryasilva/Leaflet.ExtraMarkers#48]
```
var redMarker = L.ExtraMarkers.icon({
    markerColor: 'red',
    shape: 'square',
    innerHTML: '<img src="assets/icons/fruit-vegetable.svg" width="20px" />'
  });
```

the innerHTML is added to ionClass and '>' will be added at the last of the result string by the code below:

https://github.com/coryasilva/Leaflet.ExtraMarkers/blob/a356471c96ab2f156af2d43bf606a4d765902db1/src/assets/js/leaflet.extra-markers.js#L98

**Comment by coryasilva** [comment]
The fix is shown in #48 is not an appropriate solution, but thank you for taking the time to share.  I could not reproduce.  Did you find a different solution since?
