### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by hakan42** [coryasilva/Leaflet.ExtraMarkers#50]
There has been some development going on since the 1.1.0 release (which was cut on January 2019).

Could you please cut a new release so we can use that as a webjar?

**Comment by coryasilva** [comment]
Hi @hakan42, I pushed the tags for 1.1.1, 1.20, and 1.2.1. Let me know if that works for you.

**Comment by hakan42** [comment]
Thank you, I just used the webjars site to (automatically) generate the jars. I'll tell more as soon as the artifacts are synced to maven central :)

**Comment by hakan42** [comment]
The artifacts are on maven central and work perfectly:

https://repo1.maven.org/maven2/org/webjars/bowergithub/coryasilva/leaflet.extramarkers/

Thank you again.
