### ISSUE TITLE
Cannot change markerColor of icons, other properties work

### ISSUE THREAD

**Issue by hakan42** [coryasilva/Leaflet.ExtraMarkers#51]
I am using extramarkers 1.2.1 with leaflet 1.6.0 and font-awesome 4.7.0 (not sure whether font-awesome version is relevant in this case).

I can create icons with different shapes, icon names, icon colors but cannot change "markerColor". The following:

const osmMosqueIcon = L.ExtraMarkers.icon({
    icon: 'fa-moon-o',
    markerColor: 'green',
    shape: 'round',
    prefix: 'fa'
})

still gives me the standard "red" background svg.  Changing the shape, e.g. shape: 'star' works as well.

I have verified in the Chrome network console that the markers_default.png is being successfully loaded.

Any suggestions where I could continue debugging?

**Comment by coryasilva** [comment]
I think the shape should be "circle".

**Comment by hakan42** [comment]
ah, true, it should be "circle"... Amazingly, now I can properly set the markerColor 😊
