### ISSUE TITLE
Feature Request: Use text instead of icons

### ISSUE THREAD

**Issue by pate313373** [coryasilva/Leaflet.ExtraMarkers#62]
Hi,

would be cool to use (short) text instead of icons as well.

Thanks

**Comment by coryasilva** [comment]
@pate313373 Does the poorly named `number` property work for you?

(Looking back at this project I really need to refactor...)

**Comment by pate313373** [comment]
Hahahahaha indeed, I guess 'textLabel' would be a better match.
Highly appreciate your fast answer! - Sorry, next time I'll read the documentation more carefully.
