### ISSUE TITLE
Incorrect type definition for markerColor

### ISSUE THREAD

**Issue by kancur** [coryasilva/Leaflet.ExtraMarkers#68]
Hey! 

In interface `IconOptions`, the `markerColor` should accept HEX color values as well, instead of just predefined strings (it should accept HEX values if svg is true to be precise). 

https://github.com/coryasilva/Leaflet.ExtraMarkers/blob/5722ba945cdb20574f980578184d66e50b0d1def/dist/leaflet.extra-markers.d.ts#L16-L18

Here's the implementation, it returns the original `color` parameter if not found in `colorMap`
https://github.com/coryasilva/Leaflet.ExtraMarkers/blob/5722ba945cdb20574f980578184d66e50b0d1def/src/assets/js/leaflet.extra-markers.js#L46-L61

Thank you! :-)

**Comment by adammankowski1** [comment]
@coryasilva are you going to publish this change to npm?

**Comment by coryasilva** [comment]
@adammankowski1 Good morning; I just published v1.2.2

**Comment by adammankowski1** [comment]
@coryasilva Thank you for fast response!
