### ISSUE TITLE
marker color

### ISSUE THREAD

**Issue by ra-esmith** [coryasilva/Leaflet.ExtraMarkers#74]
the list of colors is limited.
Would be great to be able to pass in an RGB value
We need a level of heat map (so color changes) and can't seem to do it easily.

**Comment by OPEN1004MIND** [comment]
I want a list of the names of the icons.
I'm guessing at the names I type with fa-icon, but I don't know what exactly is supported.
It's not even the name of the actual ionicons.designerpack, so I'm looking for a list of icon names that start with fa-.

**Comment by coryasilva** [comment]
If `svg: true` you can use the `markerColor` property to affect the svg fill. It takes a string but the string can be `hex, rgb(), rgba(), hsl(), hsla()` syntax.

**Comment by coryasilva** [comment]
open1004mind, that is out of scope for this project. Please refer to you icon library instead. The `fa-` prefix is for fontawesome.
