### ISSUE TITLE
I want a list of the names of the icons #question

### ISSUE THREAD

**Issue by OPEN1004MIND** [coryasilva/Leaflet.ExtraMarkers#78]
I'm guessing at the names I type with fa-icon, but I don't know what exactly is supported.
It's not even the name of the actual ionicons.designerpack, so I'm looking for a list of icon names that start with fa-.

ex) airplane

**Comment by coryasilva** [comment]
The list of icons come should be documented in the external icon library of your choice.  In other words, you must bring your own icon library and that library must have a CSS class API.
