### ISSUE TITLE
Auto resize 

### ISSUE THREAD

**Issue by winanjayaamijoyo** [coryasilva/Leaflet.ExtraMarkers#79]
Hi there,

the marker (fa-number) doesn't have enough space or it's not automatically resize when I enter the number like 9,999.
do you have any plan to enhance it? or did I miss something to make it auto-resize?

I look forward to hear from you.
thank you

**Comment by coryasilva** [comment]
Hi. I have no plans to support this, though, it seems out of scope and rather belongs to a  labeling lib/feature.
