### ISSUE TITLE
Wiredep not recognizing "main" section of bower.json

### ISSUE THREAD

**Issue by cyrilchaponeverysens** [coryasilva/Leaflet.ExtraMarkers#8]
Tools that parse *bower.json* file, such as [wiredep](https://github.com/taptapship/wiredep), are not able to recognize current `main` section.

**Comment by cyrilchaponeverysens** [comment]
Temporary fix for community :

add this section to your project's *bower.json*

```
  "overrides": {
    "Leafet.extra-markers": {
      "main": [
        "src/leaflet.extra-markers.css",
        "src/leaflet.extra-markers.less",
        "src/leaflet.extra-markers.js"
      ]
    }
  }
```

**Comment by coryasilva** [comment]
lol, whoa never noticed that one.  oops!
